using UnityEngine;
using UnityEngine.Audio;

namespace Devolfer.Sound
{
    /// <summary>
    /// Mimics the public sound properties found in an <see cref="AudioSource"/>.
    /// </summary>
    public class SoundProperties
    {
        /// <summary>
        /// The default AudioClip to play.
        /// </summary>
        public AudioClip Clip;

        /// <summary>
        /// The target group to which the AudioSource should route its signal.
        /// </summary>
        public AudioMixerGroup OutputAudioMixerGroup;

        /// <summary>
        /// Mute sets the volume = 0, Un-Mute restore the original volume.
        /// </summary>
        public bool Mute;

        /// <summary>
        /// Bypass effects (Applied from filter components or global listener filters).
        /// </summary>
        public bool BypassEffects;

        /// <summary>
        /// When set global effects on the AudioListener will not be applied to the audio signal generated by the AudioSource. Does not apply if the AudioSource is playing into a mixer group.
        /// </summary>
        public bool BypassListenerEffects;

        /// <summary>
        /// When set doesn't route the signal from an AudioSource into the global reverb associated with reverb zones.
        /// </summary>
        public bool BypassReverbZones;
        
        /// <summary>
        /// If set to true, the audio source will automatically start playing on awake.
        /// </summary>
        public bool PlayOnAwake;
        
        /// <summary>
        /// Is the audio clip looping?
        /// </summary>
        public bool Loop;
        
        /// <summary>
        /// Sets the priority of the AudioSource.
        /// </summary>
        /// <remarks>0 = High, 256 = Low</remarks>
        [Range(0, 256)] public int Priority;
        
        /// <summary>
        /// The volume of the audio source (0.0 to 1.0).
        /// </summary>
        [Range(0, 1)] public float Volume;
        
        /// <summary>
        /// The pitch of the audio source.
        /// </summary>
        [Range(-3, 3)] public float Pitch;
        
        /// <summary>
        /// Pans a playing sound in a stereo way (left or right). This only applies to sounds that are Mono or Stereo.
        /// </summary>
        /// <remarks>-1 = Left, 1 = Right</remarks>
        [Range(-1, 1)] public float PanStereo;
        
        /// <summary>
        /// Sets how much the AudioSource is affected by 3D spatialisation calculations (attenuation, doppler etc).
        /// </summary>
        /// <remarks>0 = 2D, 1 = 3D</remarks>
        [Range(0, 1)] public float SpatialBlend;
        
        /// <summary>
        /// The amount by which the signal from the AudioSource will be mixed into the global reverb associated with the Reverb Zones.
        /// </summary>
        [Range(0, 1.1f)] public float ReverbZoneMix;

        /// <summary>
        /// Sets the Doppler scale for the AudioSource.
        /// </summary>
        [Range(0, 5)] public float DopplerLevel;
        
        /// <summary>
        /// Sets the spread angle (in degrees) of a 3d stereo or multichannel sound in speaker space.
        /// </summary>
        [Range(0, 360)] public float Spread;
        
        /// <summary>
        /// Sets how the AudioSource attenuates over distance.
        /// </summary>
        public AudioRolloffMode RolloffMode;
        
        /// <summary>
        /// Within the Min distance the AudioSource will cease to grow louder in volume.
        /// </summary>
        public float MinDistance;
        
        /// <summary>
        /// (Logarithmic rolloff) MaxDistance is the distance a sound stops attenuating at.
        /// </summary>
        public float MaxDistance;

        /// <param name="clip">The clip to be played.</param>
        public SoundProperties(AudioClip clip)
        {
            Clip = clip;
            OutputAudioMixerGroup = null;
            Mute = false;
            BypassEffects = false;
            BypassListenerEffects = false;
            BypassReverbZones = false;
            PlayOnAwake = true;
            Loop = false;
            Priority = 128;
            Volume = 1;
            Pitch = 1;
            PanStereo = 0;
            SpatialBlend = 0;
            ReverbZoneMix = 1;
            DopplerLevel = 1;
            Spread = 0;
            RolloffMode = AudioRolloffMode.Logarithmic;
            MinDistance = 1;
            MaxDistance = 500;
        }

        /// <param name="properties">The properties of the original.</param>
        public SoundProperties(SoundProperties properties)
        {
            Clip = properties.Clip;
            OutputAudioMixerGroup = properties.OutputAudioMixerGroup;
            Mute = properties.Mute;
            BypassEffects = properties.BypassEffects;
            BypassListenerEffects = properties.BypassListenerEffects;
            BypassReverbZones = properties.BypassReverbZones;
            PlayOnAwake = properties.PlayOnAwake;
            Loop = properties.Loop;
            Priority = properties.Priority;
            Volume = properties.Volume;
            Pitch = properties.Pitch;
            PanStereo = properties.PanStereo;
            SpatialBlend = properties.SpatialBlend;
            ReverbZoneMix = properties.ReverbZoneMix;
            DopplerLevel = properties.DopplerLevel;
            Spread = properties.Spread;
            RolloffMode = properties.RolloffMode;
            MinDistance = properties.MinDistance;
            MaxDistance = properties.MaxDistance;
        }

        /// <summary>
        /// Applies all properties on the referenced AudioSource.
        /// </summary>
        /// <param name="audioSource">AudioSource by reference.</param>
        public void ApplyOn(ref AudioSource audioSource)
        {
            audioSource.clip = Clip;
            audioSource.outputAudioMixerGroup = OutputAudioMixerGroup;
            audioSource.mute = Mute;
            audioSource.bypassEffects = BypassEffects;
            audioSource.bypassListenerEffects = BypassListenerEffects;
            audioSource.bypassReverbZones = BypassReverbZones;
            audioSource.playOnAwake = PlayOnAwake;
            audioSource.loop = Loop;
            audioSource.priority = Priority;
            audioSource.volume = Volume;
            audioSource.pitch = Pitch;
            audioSource.panStereo = PanStereo;
            audioSource.spatialBlend = SpatialBlend;
            audioSource.reverbZoneMix = ReverbZoneMix;
            audioSource.dopplerLevel = DopplerLevel;
            audioSource.spread = Spread;
            audioSource.rolloffMode = RolloffMode;
            audioSource.minDistance = MinDistance;
            audioSource.maxDistance = MaxDistance;
        }

        /// <summary>
        /// Sets all public properties of the referenced AudioSource to their default values.
        /// </summary>
        /// <param name="audioSource">AudioSource by reference.</param>
        public static void ResetOn(ref AudioSource audioSource)
        {
            audioSource.clip = null;
            audioSource.outputAudioMixerGroup = null;
            audioSource.mute = false;
            audioSource.bypassEffects = false;
            audioSource.bypassListenerEffects = false;
            audioSource.bypassReverbZones = false;
            audioSource.playOnAwake = true;
            audioSource.loop = false;
            audioSource.priority = 128;
            audioSource.volume = 1;
            audioSource.pitch = 1;
            audioSource.panStereo = 0;
            audioSource.spatialBlend = 0;
            audioSource.reverbZoneMix = 1;
            audioSource.dopplerLevel = 1;
            audioSource.spread = 0;
            audioSource.rolloffMode = AudioRolloffMode.Logarithmic;
            audioSource.minDistance = 1;
            audioSource.maxDistance = 500;
        }

        public static implicit operator SoundProperties(AudioSource audioSource) =>
            new(audioSource.clip)
            {
                Clip = audioSource.clip,
                OutputAudioMixerGroup = audioSource.outputAudioMixerGroup,
                Mute = audioSource.mute,
                BypassEffects = audioSource.bypassEffects,
                BypassListenerEffects = audioSource.bypassListenerEffects,
                BypassReverbZones = audioSource.bypassReverbZones,
                PlayOnAwake = audioSource.playOnAwake,
                Loop = audioSource.loop,
                Priority = audioSource.priority,
                Volume = audioSource.volume,
                Pitch = audioSource.pitch,
                PanStereo = audioSource.panStereo,
                SpatialBlend = audioSource.spatialBlend,
                ReverbZoneMix = audioSource.reverbZoneMix,
                DopplerLevel = audioSource.dopplerLevel,
                Spread = audioSource.spread,
                RolloffMode = audioSource.rolloffMode,
                MinDistance = audioSource.minDistance,
                MaxDistance = audioSource.maxDistance
            };
    }
}